### ISSUE TITLE
errors in gradio/anyio/scripts

### ISSUE THREAD

**Issue by dakky221** [sammyf/Autobooga#11]
I'm pretty sure it installed OK because when using wrong server it says it cant find it or theres no JSON output... but when using the correct server with json (mdosch.de), this pops up...

`Output generated in 3.82 seconds (4.71 tokens/s, 18 tokens, context 174, seed 537079860)
Filename found : ''
Query found : mira
Url found :

Traceback (most recent call last):
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\ooga\oobabooga_windows\text-generation-webui\modules\chat.py", line 304, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "C:\ooga\oobabooga_windows\text-generation-webui\modules\chat.py", line 289, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\ooga\oobabooga_windows\text-generation-webui\modules\chat.py", line 201, in chatbot_wrapper
    text = apply_extensions('input', text, state, is_chat=True)
  File "C:\ooga\oobabooga_windows\text-generation-webui\modules\extensions.py", line 223, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\ooga\oobabooga_windows\text-generation-webui\modules\extensions.py", line 81, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "C:\ooga\oobabooga_windows\text-generation-webui\extensions\Autobooga\script.py", line 364, in input_modifier
    write_log(character, "\n\n("+_now+") USER > "+prompt+"\n")
  File "C:\ooga\oobabooga_windows\text-generation-webui\extensions\Autobooga\script.py", line 70, in write_log
    f.write(s)
  File "C:\ooga\oobabooga_windows\installer_files\env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2609' in position 305: character maps to <undefined>`

Don't have a clue what's wrong

**Comment by dakky221** [comment]
Looks to me like charset issue, it's trying to load utf-8 under cp1252, of course it gets wrong characters. Should be a simple fix?

**Comment by dakky221** [comment]
It actually helped editing script.py and adding 
`encoding="utf-8" `
to the read lines, eg. 
`with open(fname, 'r', encoding="utf-8") as f:`

now it returns no errors, and I can see it searches the internet for the terms, but it doesn't writes them in the output

**Comment by sammyf** [comment]
yes... it's apparently a common problem when you run python in Windows. The "fix" is for you to set the the environment variable PYTHONUTF8=1

see also : https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

As I don't have a Windows  running on any of my systems I can not help you further on that problem, sorry.
