### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dillfrescott** [sammyf/Autobooga#4]
```
Traceback (most recent call last):
  File "C:\Users\micro\miniconda3\envs\text\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\micro\miniconda3\envs\text\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\micro\miniconda3\envs\text\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\micro\miniconda3\envs\text\lib\http\server.py", line 433, in handle
    self.handle_one_request()
  File "C:\Users\micro\miniconda3\envs\text\lib\http\server.py", line 421, in handle_one_request
    method()
  File "C:\Users\micro\OneDrive\Desktop\text-generation-webui\extensions\openai\script.py", line 476, in do_POST
    for a in generator:
  File "C:\Users\micro\OneDrive\Desktop\text-generation-webui\modules\text_generation.py", line 27, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "C:\Users\micro\OneDrive\Desktop\text-generation-webui\modules\text_generation.py", line 193, in _generate_reply
    question = apply_extensions('input', question, state)
  File "C:\Users\micro\OneDrive\Desktop\text-generation-webui\modules\extensions.py", line 199, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\Users\micro\OneDrive\Desktop\text-generation-webui\modules\extensions.py", line 62, in _apply_string_extensions
    text = func(text, state)
  File "C:\Users\micro\OneDrive\Desktop\text-generation-webui\extensions\Autobooga\script.py", line 208, in input_modifier
    character = state["character_menu"]
KeyError: 'character_menu'
```

**Comment by sammyf** [comment]
fixed in the latest release which should be out today. That's what happens when you write two extensions with similar code at the same time : autobooga ended up with Moztts config file, and I don't (didn't) check whether the config was valid. Sorry  for the inconvenience.

**Comment by dillfrescott** [comment]
Its ok. Thanks for the update!

**Comment by sammyf** [comment]
should be fixed. Added some other nice stuff too :)

**Comment by sammyf** [comment]
closing the issue. Please reopen if it persists.

**Comment by mawhin** [comment]
Perhaps I should be using a different url? I loaded the extension from within tgwui using the url provided. Did it only today. Installed tgwui with the oneclick installer on win11. Exactly the same error every time. Hope it's me doing a inadequate think.

**Comment by jmoney7823956789378** [comment]
> closing the issue. Please reopen if it persists.

This issue still persists (in a similar error) when using the oobabooga api, this is likely because there's no condition for the extension to check if it's using the gradio ui or being queried from the api, since there's no "character_menu".
Here is the error log:

```
Traceback (most recent call last):
  File "/home/jm/miniconda3/envs/textgen/lib/python3.10/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/home/jm/miniconda3/envs/textgen/lib/python3.10/site-packages/websockets/legacy/server.py", line 1186, in _ws_handler
    return await cast(
  File "/opt/text-generation-webui/extensions/api/streaming_api.py", line 89, in _handle_connection
    await _handle_stream_message(websocket, message)
  File "/opt/text-generation-webui/extensions/api/util.py", line 143, in api_wrapper
    return await func(*args, **kwargs)
  File "/opt/text-generation-webui/extensions/api/streaming_api.py", line 34, in _handle_stream_message
    for a in generator:
  File "/opt/text-generation-webui/modules/text_generation.py", line 28, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "/opt/text-generation-webui/modules/text_generation.py", line 189, in _generate_reply
    question = apply_extensions('input', question, state)
  File "/opt/text-generation-webui/modules/extensions.py", line 207, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/opt/text-generation-webui/modules/extensions.py", line 61, in _apply_string_extensions
    text = func(text, state)
  File "/opt/text-generation-webui/extensions/Autobooga/script.py", line 336, in input_modifier
    character = state["character_menu"]+"("+shared.model_name+")"
KeyError: 'character_menu'
```

**Comment by sammyf** [comment]
pull and try again. I had this already fixed locally, but I was too busy playing BG3 to merge ;)
